src/0-Presentation/Crm.Mvc/Controllers/PermissionController.cs
using Crm.Application.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Crm.Mvc.Controllers
{
    [Authorize]
    public class PermissionController : Controller
    {
        private readonly IPermissionAppService _permissionAppService;

        public PermissionController(IPermissionAppService permissionAppService)
        {
            _permissionAppService = permissionAppService;
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public IActionResult Index()
        {
            var consultaUsuarioViewModel = _permissionAppService.ListAllUsers();

            return View(consultaUsuarioViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public IActionResult RolesList()
        {
            var roleList = _permissionAppService.ListAllRoles();

            return View(roleList);
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        public IActionResult UserPermission()
        {


            return View();
        }
    }
}

src/0-Presentation/Crm.Mvc/Controllers/UsuarioController.cs
using Crm.Application.Interface;
using Crm.Application.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Crm.Mvc.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioAppService _usuarioAppService;

        public UsuarioController(IUsuarioAppService usuarioAppService)
        {
            _usuarioAppService = usuarioAppService;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            try
            {
                var listaUsuario = _usuarioAppService.GetAllUsuarioViewModel();

                return View(listaUsuario);
            }
            catch (Exception)
            {
                return View(new List<UsuarioViewModel>());
            }
        }

        [HttpGet]
        [Authorize(Policy = "RemoverUsuario")]
        public IActionResult CadastroUsuario()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "RemoverUsuario")]
        public IActionResult CadastroUsuario(UsuarioViewModel usuarioViewModel)
        {
            try
            {
                if (!ModelState.IsValid) return View(usuarioViewModel);

                _usuarioAppService.Cadastrar(usuarioViewModel);

                return View(new UsuarioViewModel());
            }
            catch (Exception)
            {
                return View(usuarioViewModel);
            }
        }
    }
}

src/0-Presentation/Crm.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc</title>

    <link rel="stylesheet" href="~/lib/materialize/css/materialize.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <partial name="_menu" controller="" />

    <main role="main">

        <div class="row">
            <div>
                <partial name="_CookieConsentPartial" />
                @RenderBody()
            </div>
        </div>
    </main>

    <partial name="_footer" />

    <script src="~/lib/materialize/js/materialize.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    @RenderSection("Scripts", false)

</body>
</html>

src/0-Presentation/Crm.Mvc/Views/Shared/_footer.cshtml
<footer class="page-footer">
    <div class="footer-copyright">
        <div class="container">
            ©@DateTime.Now.Year Copyright
        </div>
    </div>
</footer>

src/0-Presentation/Crm.Mvc/Views/Shared/_menu.cshtml
@using Crm.Domain.Models.Permission
@using Crm.Infra.CrossCutting.Identity.Models
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<style>

    #logo-container {
        height: 57px;
        margin-bottom: 32px;
    }

    li.logo {
        text-align: center;
        margin-top: 32px;
        margin-bottom: 70px;
    }

    #front-page-logo {
        display: inline-block;
        height: 100%;
        pointer-events: none;
    }

    #slide_menu li.version {
        position: absolute;
        top: 100px;
        left: 0;
        right: 0;
        font-family: "Inconsolata";
        text-align: center;
    }

    .sidenav .collapsible {
        margin: 0;
    }

    ul.sidenav.sidenav-fixed ul.collapsible-accordion {
        background-color: #FFF;
    }

    .sidenav .collapsible, .sidenav.fixed .collapsible {
        border: none;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    .no-padding {
        padding: 0 !important;
    }
</style>

<nav>
    <div class="nav-wrapper">
        <div class="container">
            <ul class="hide-on-med-and-down left">
                <li>
                    <a href="#" class="sidenav-trigger show-on-large" data-target="slide_menu"><i class="material-icons">menu</i></a>
                </li>
            </ul>

            <a href="#" class="brand-logo sidenav-trigger left" data-target="slide_menu"><i class="material-icons left">menu</i></a>
            <a class="brand-logo center" asp-area="" asp-controller="Home" asp-action="Index">Mvc</a>
            <a href="#" class="sidenav-trigger right" data-target="slide_login"><i class="material-icons right">person</i></a>

            <ul class="hide-on-med-and-down right">
                @if (SignInManager.IsSignedIn(User))
                {
                    <li>
                        <a href="#" class="sidenav-trigger show-on-large" data-target="slide_login"><i class="material-icons left">person</i>@UserManager.GetUserName(User)</a>
                    </li>
                }
                else
                {
                    <li>
                        <a class="sidenav-trigger show-on-large" method="post" asp-controller="Account" asp-action="Login"><i class="material-icons left">lock</i>Login</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>

<ul class="sidenav" id="slide_menu">
    @if (User.Identity.IsAuthenticated)
    {
        <li class="logo">
            <a id="logo-container" class="brand-logo" href="/">
                <object id="front-page-logo" data="imagens/logoPadrao.png"></object>
            </a>
        </li>
        <li class="version">
            <a href="/">Mvc</a>
        </li>
        <li>
            <div class="divider"></div>
        </li>
        <li>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="collapsible-header waves-effect waves-teal">Home<i class="material-icons">home</i></a>
        </li>
        <li>
            <div class="divider"></div>
        </li>
        <li>
            <a asp-area="" asp-controller="Home" asp-action="Privacy" class="collapsible-header waves-effect waves-teal">Privacidade<i class="material-icons">message</i></a>
        </li>
        <li>
            <div class="divider"></div>
        </li>
        <li>
            <ul class="collapsible collapsible-accordion">
                <li>
                    <a class="collapsible-header waves-effect waves-teal">Usuario<i class="material-icons">arrow_drop_down</i></a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a asp-area="" asp-controller="Usuario" asp-action="Index" class="waves-effect waves-teal">Lista Usuarios<i class="material-icons">list</i></a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Usuario" asp-action="CadastroUsuario" class="waves-effect waves-teal">Cadastro Usuarios<i class="material-icons">list</i></a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
        if (User.IsInRole("User"))
         {
             <li>
                 <div class="divider"></div>
             </li>
             <li>
                 <ul class="collapsible collapsible-accordion">
                     <li>
                         <a class="collapsible-header waves-effect waves-teal">Permissões<i class="material-icons">arrow_drop_down</i></a>
                         <div class="collapsible-body">
                             <ul>
                                 <li>
                                     <a asp-area="" asp-controller="Permission" asp-action="Index" class="waves-effect waves-teal">Lista Usuarios<i class="material-icons">list</i></a>
                                 </li>
                                 <li>
                                     <a asp-area="" asp-controller="Permission" asp-action="RolesList" class="waves-effect waves-teal">Lista Permissões<i class="material-icons">list</i></a>
                                 </li>
                             </ul>
                         </div>
                     </li>
                 </ul>
             </li>
         }
        <li>
            <div class="divider"></div>
        </li>
    }
</ul>


@await Html.PartialAsync("_LoginPartial")

<script language="javascript">

    document.addEventListener('DOMContentLoaded', function () {
        const menuOptions = {};
        const loginOptions = { edge: 'right' };
        const collapsibleOptions = { inDuration: 50, outDuration: 50 };

        const menu = document.querySelectorAll('#slide_menu');
        M.Sidenav.init(menu, menuOptions);

        const login = document.querySelectorAll('#slide_login');
        M.Sidenav.init(login, loginOptions);

        const elems = document.querySelectorAll('.collapsible');
        M.Collapsible.init(elems, collapsibleOptions);
    });

</script>